=== nevenaprokic/XML-project/docs/xml-schema/P-1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.ftn.uns.ac.rs/p1" xmlns:p1="http://www.ftn.uns.ac.rs/p1">

    <xs:element name="Zahtev_za_priznanje_patenta">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Primalac_zahteva" type="p1:TPrimalac_zahteva"/>
                <xs:element ref="p1:Pronalazak"/>
                <xs:element name="Podnosilac_prijave" type="p1:TLice"/>
                <xs:element name="Pronalazac" type="p1:TPronalazac"/>
                <xs:element name="Punomocnik" type="p1:TPunomocnik"/>
                <xs:element ref="p1:Podaci_o_dostavljanju"/>
                <xs:element name="Zahtev_za_priznanje_prvenstva_iz_ranijih_prijava"
                    type="p1:TZahtev_za_priznanje_prava_prvenstva_iz_ranijih_prijava"/>
            </xs:sequence>
            <xs:attribute name="broj_prijave" type="xs:string" use="required"/>
            <xs:attribute name="datum_prijema_prijave" type="xs:date" use="required"/>
            <xs:attribute name="priznati_datum_podnosenja" type="xs:date" use="required"/>
            <xs:attribute name="tip_prijave" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="dopunska"/>
                        <xs:enumeration value="izdvojena"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="Adresa">
        <xs:complexType>
            <xs:all>
                <xs:element name="Drzava" type="xs:string"/>
                <xs:element name="Grad" type="xs:string"/>
                <xs:element name="Ulica" type="xs:string"/>
                <xs:element name="Broj" type="xs:positiveInteger"/>
                <xs:element name="Postanski_broj">
                    <xs:simpleType>
                        <xs:restriction base="xs:positiveInteger">
                            <xs:totalDigits value="5"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
    <xs:element name="Kontakt_podaci">
        <xs:complexType>
            <xs:all>
                <xs:element name="Telefon" type="xs:int"> </xs:element>
                <xs:element name="Faks" type="xs:string"/>
                <xs:element name="Email">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[^@]+@[^\.]+\..+"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
    <xs:element name="Pronalazak">
        <xs:complexType>
            <xs:all>
                <xs:element name="Naziv_na_srpskom" type="xs:string"/>
                <xs:element name="Naziv_na_engleskom" type="xs:string"/>
            </xs:all>
        </xs:complexType>
    </xs:element>
    <xs:element name="Podaci_o_dostavljanju">
        <xs:complexType>
            <xs:all>
                <xs:element ref="p1:Adresa"/>
                <xs:element name="Nacin_dostavljanja">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="elektronski"/>
                            <xs:enumeration value="papirna_forma"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
    <xs:element name="Ranija_prijava">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Datum_podnosenja" type="xs:date"/>
                <xs:element name="Broj_prijave" type="xs:string"/>
                <xs:element name="Dvoslovna_oznaka_drzave">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:length value="2"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType abstract="true" name="TLice">
        <xs:sequence>
            <xs:element ref="p1:Adresa"/>
            <xs:element ref="p1:Kontakt_podaci"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TPravno_lice">
        <xs:complexContent>
            <xs:extension base="p1:TLice">
                <xs:sequence maxOccurs="1" minOccurs="1">
                    <xs:element maxOccurs="1" minOccurs="1" name="Naziv"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TFizicko_lice">
        <xs:complexContent mixed="false">
            <xs:extension base="p1:TLice">
                <xs:sequence maxOccurs="1" minOccurs="1">
                    <xs:element name="Ime" type="xs:string" maxOccurs="1" minOccurs="1"/>
                    <xs:element name="Prezime" type="xs:string" maxOccurs="1" minOccurs="1"/>
                    <xs:element name="Drzavljanstvo" maxOccurs="1" minOccurs="1" type="xs:string">
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TPrimalac_zahteva">
        <xs:all>
            <xs:element ref="p1:Adresa"/>
            <xs:element fixed="Zavod za intelektualnu svojinu" name="Naziv"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="TPronalazac">
        <xs:complexContent>
            <xs:extension base="p1:TFizicko_lice">
                <xs:attribute name="anoniman" type="xs:boolean" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TPunomocnik">
        <xs:complexContent>
            <xs:extension base="p1:TLice">
                <xs:attribute name="za_prijem_pismena" type="xs:boolean" use="required"/>
                <xs:attribute name="za_zastupanje" type="xs:boolean" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TZahtev_za_priznanje_prava_prvenstva_iz_ranijih_prijava">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="0" ref="p1:Ranija_prijava"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== nevenaprokic/XML-project/docs/XMLParsers/data/Zahtev_za_priznanje_patenta.xml
<?xml version="1.0" encoding="UTF-8"?>
<Zahtev_za_priznanje_patenta xmlns="http://www.ftn.uns.ac.rs/p1"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/p1 file:/C:/fakultet/7.%20semestar/XML/Projekat/XML-project/docs/xml-schema/P-1.xsd"
    broj_prijave="P3" datum_prijema_prijave="2022-09-24-06:00" priznati_datum_podnosenja="2022-09-25-06:00" tip_prijave="izdvojena">
    <Primalac_zahteva>
        <Adresa>
            <Drzava>Republika Srbija</Drzava>
            <Grad>Beograd</Grad>
            <Ulica>Kneginje Ljubice</Ulica>
            <Broj>12</Broj>
            <Postanski_broj>21000</Postanski_broj>
        </Adresa>
        <Naziv>Zavod za intelektualnu svojinu</Naziv>
    </Primalac_zahteva>
    <Pronalazak>
        <Naziv_na_srpskom>Patent1</Naziv_na_srpskom>
        <Naziv_na_engleskom>Patent1</Naziv_na_engleskom>
    </Pronalazak>
    <Pronalazac anoniman="false">
        <Adresa>
            <Drzava>Republika Srbija</Drzava>
            <Grad>Kikinda</Grad>
            <Ulica>Svetosavska</Ulica>
            <Broj>1</Broj>
            <Postanski_broj>23300</Postanski_broj>
        </Adresa>
        <Kontakt_podaci>
            <Telefon>0654332221</Telefon>
            <Faks>0230/111333</Faks>
            <Email>nl@gmail.com</Email>
        </Kontakt_podaci>
        <Ime>Natasa</Ime>
        <Prezime>Lakovic</Prezime>
        <Drzavljanstvo>Republika Srbija</Drzavljanstvo>
    </Pronalazac> 
    <Podnosilac_zahteva>
        <Lice xsi:type="TPravno_lice">
            <Adresa>
                <Drzava>Republika Srbija</Drzava>
                <Grad>Novi Sad</Grad>
                <Ulica>Radnicka</Ulica>
                <Broj>21</Broj>
                <Postanski_broj>21000</Postanski_broj>
            </Adresa>
            <Kontakt_podaci>
                <Telefon>067122290</Telefon>
                <Faks>021/201222</Faks>
                <Email>katarina@gmail.com</Email>
            </Kontakt_podaci>
            <Naziv>Ustanova1</Naziv>
        </Lice>
        <pronalazac>false</pronalazac>
    </Podnosilac_zahteva>
    <Punomocnik>
        <Lice xsi:type="TFizicko_lice">
            <Adresa>
                <Drzava>Republika Srbija</Drzava>
                <Grad>Novi Sad</Grad>
                <Ulica>Marije Bursać</Ulica>
                <Broj>1</Broj>
                <Postanski_broj>21000</Postanski_broj>
            </Adresa>
            <Kontakt_podaci>
                <Telefon>067899000</Telefon>
                <Faks>021/2022000</Faks>
                <Email>n@gmail.com</Email>
            </Kontakt_podaci>
            <Ime>Petar</Ime>
            <Prezime>Petrović</Prezime>
            <Drzavljanstvo>Republika Srbija</Drzavljanstvo>
        </Lice>
        <za_zastupanje>true</za_zastupanje>
        <za_prijem_pismena>false</za_prijem_pismena>
    </Punomocnik>
    <Podaci_o_dostavljanju>
        <Adresa>
            <Drzava>Republika Srbija</Drzava>
            <Grad>Novi Sad</Grad>
            <Ulica>Bulevar oslobodjenja</Ulica>
            <Broj>21</Broj>
            <Postanski_broj>21000</Postanski_broj>
        </Adresa>
        <Nacin_dostavljanja>elektronski</Nacin_dostavljanja>
    </Podaci_o_dostavljanju>
    <Zahtev_za_priznanje_prvenstva_iz_ranijih_prijava>
        <Ranija_prijava>
            <Datum_podnosenja>2022-09-24-06:00</Datum_podnosenja>
            <Broj_prijave>P2</Broj_prijave>
            <Dvoslovna_oznaka_drzave>RS</Dvoslovna_oznaka_drzave>
        </Ranija_prijava>
    </Zahtev_za_priznanje_prvenstva_iz_ranijih_prijava>
</Zahtev_za_priznanje_patenta>
