=== nevenaprokic/XML-project/docs/XMLParsers/data/A1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="www.ftn.uns.ac.rs/ZahtevZaAutorskoDelo"
    xmlns:а1="www.ftn.uns.ac.rs/ZahtevZaAutorskoDelo">
    
    <xs:element name="Zahtev_za_autorsko_delo">
        <xs:complexType>
            <xs:all>
                <xs:element name="Zavod" type="а1:TPravno_lice"> </xs:element>
                <xs:element name="Podnosilac">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="Email" type="xs:string" minOccurs="0"/>
                            <xs:element name="Telefon" nillable="true" type="xs:string"
                                minOccurs="0"/>
                            <xs:element minOccurs="1" name="Podaci_o_podnosiocu"
                                type="а1:TPodnosilac"/>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Autorsko_delo" minOccurs="1" type="а1:TAutorsko_delo"/>
                <xs:element name="Prilozi" form="qualified" minOccurs="0" nillable="true"
                    type="а1:TPrilog"/>
            </xs:all>
            <xs:attribute fixed="ЗАХТЕВ ЗА УНОШЕЊЕ У ЕВИДЕНЦИЈУ И ДЕПОНОВАЊЕ АУТОРСКИХ ДЕЛА"
                name="naslov" type="xs:string"/>
            <xs:attribute name="broj_prijave" type="xs:string"/>
            <xs:attribute name="datum_podnosenja" type="xs:date"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Adresa" nillable="true">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Mesto" type="xs:string"/>
                <xs:element name="Ulica" type="xs:string"/>
                <xs:element name="Broj" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TFizicko_lice">
        <xs:sequence>
            <xs:element name="Ime" type="xs:string"/>
            <xs:element name="Prezime" type="xs:string"/>
            <xs:element ref="а1:Adresa"/>
            <xs:element name="Drzavljanstvo" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TPravno_lice">
        <xs:sequence>
            <xs:element name="Naziv" type="xs:string"/>
            <xs:element ref="а1:Adresa"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TAutor">
        <xs:complexContent>
            <xs:extension base="а1:TFizicko_lice">
                <xs:sequence>
                    <xs:element name="Pseudonim" nillable="true" type="xs:string" minOccurs="0"/>
                    <xs:element name="Godina_smrti" nillable="true" type="xs:integer" minOccurs="0"/>
                </xs:sequence>
                <xs:attribute name="primarni" type="xs:boolean"/>
                <xs:attribute name="anonimni" type="xs:boolean"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TAutori">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="Autor" type="а1:TAutor"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TPodnosilac">
        <xs:choice>
            <xs:element minOccurs="0" name="Autor" type="а1:TAutor"/>
            <xs:element name="Punomocnik" nillable="true" type="а1:TFizicko_lice" minOccurs="0"/>
            <xs:element name="Pravno_lice" nillable="true" type="а1:TPravno_lice" minOccurs="0"/>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="TAutorsko_delo">
        <xs:complexContent>
            <xs:extension base="а1:TOsnovni_podaci_o_delu">
                <xs:sequence>
                    <xs:element minOccurs="0" name="Podaci_o_originalu" nillable="true"
                        type="а1:TOsnovni_podaci_o_delu"/>
                    <xs:element name="Radni_odnos" type="xs:string" minOccurs="0" nillable="true"/>
                    <xs:element name="Nacin_koriscenja" type="xs:string" minOccurs="0"
                        nillable="true"/>
                </xs:sequence>
                <xs:attribute name="vrsta" type="а1:vrsta_autorskog_dela"/>
                <xs:attribute name="forma_zapisa" type="а1:forma_zapisa_autorskog_dela"/>
                <xs:attribute name="prerada" type="xs:boolean"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:simpleType name="vrsta_autorskog_dela">
        <xs:restriction base="xs:string">
            <xs:enumeration value="knjizevno delo"/>
            <xs:enumeration value="muzicko delo"/>
            <xs:enumeration value="likovno delo"/>
            <xs:enumeration value="racunarski program"/>
            <xs:enumeration value="ostalo"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="forma_zapisa_autorskog_dela">
        <xs:restriction base="xs:string">
            <xs:enumeration value="stamparski tekst"/>
            <xs:enumeration value="opticki disk"/>
            <xs:enumeration value="ostalo"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="TOsnovni_podaci_o_delu">
        <xs:sequence>
            <xs:element name="Identifikator">
                <xs:complexType>
                    <xs:all>
                        <xs:element name="Naslov" type="xs:string"/>
                        <xs:element name="Alternativni_naslov" minOccurs="0" nillable="true"
                            type="xs:string"/>
                    </xs:all>
                </xs:complexType>
            </xs:element>
            <xs:element name="Autori" type="а1:TAutori"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TPrilog">
        <xs:all>
            <xs:element name="Prisutan_opis" type="xs:boolean"/>
            <xs:element name="Prisutan_primer" type="xs:boolean"/>
        </xs:all>
    </xs:complexType>
</xs:schema>

=== nevenaprokic/XML-project/projekat/autorskoDelo/src/main/resources/data/A1.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../xsl/grddl.xsl"?>

<Zahtev_za_autorsko_delo 
	xmlns="http://ftn.uns.ac.rs/a1" 
	xmlns:zaj="http://www.ftn.uns.ac.rs/zaj" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://ftn.uns.ac.rs/a1 ./A1.xsd"

    naslov="ZAHTEV ZA UNOSENJE U EVIDENCIJU I DEPONOVANJE AUTORSKIH DELA"
    broj_prijave='A-100'
    datum_podnosenja="2022-12-08"
    status="neobradjen">

    <Zavod>
	    <zaj:Adresa>
	      <zaj:Grad>Beograd</zaj:Grad>
	      <zaj:Ulica>Kneginje Ljubice</zaj:Ulica>
	      <zaj:Broj>2</zaj:Broj>
	    </zaj:Adresa>
	    <Naziv>Zavod za intelektualnu svojinu</Naziv>
    </Zavod>

    <Podnosilac>
     	<Pravno_lice xsi:type="zaj:TPravno_lice">
        	<zaj:Adresa>
                <zaj:Grad>Novi Sad</zaj:Grad>
                <zaj:Ulica>Urosa Predica</zaj:Ulica>
                <zaj:Broj>7</zaj:Broj>
            </zaj:Adresa>
            <zaj:Kontakt_podaci>
	            <zaj:Telefon>065/222-3332</zaj:Telefon>
	            <zaj:Email>pera@gmail.com</zaj:Email>
       		</zaj:Kontakt_podaci>
        	<zaj:Naziv>Pera organization</zaj:Naziv>
        </Pravno_lice>
       
    </Podnosilac>

    <Autorsko_delo vrsta="racunarski program" forma_zapisa="ostalo" prerada="true">
        
        <Identifikator>
            <Naslov>XML</Naslov>
            <Alternativni_naslov>A1</Alternativni_naslov>
        </Identifikator>
        
        <Autori>
            <Autor primarni="true" xsi:type="TAutor">
             	<zaj:Adresa>
                    <zaj:Grad>Novi Sad</zaj:Grad>
                    <zaj:Ulica>Maksima Gorkog</zaj:Ulica>
                    <zaj:Broj>46</zaj:Broj>
                </zaj:Adresa>
                <zaj:Kontakt_podaci>
                	<zaj:Telefon>065/222-3332</zaj:Telefon>
	            	<zaj:Email>kk@gmail.com</zaj:Email>
	            </zaj:Kontakt_podaci>
                <zaj:Ime>Katarina</zaj:Ime>
                <zaj:Prezime>Komad</zaj:Prezime>
               
                <zaj:Drzavljanstvo>Srpsko</zaj:Drzavljanstvo>
            </Autor>

            <Autor anonimni="true" primarni="false">
                <zaj:Adresa>
                    <zaj:Grad>Nis</zaj:Grad>
                    <zaj:Ulica>Bulevar Oslobodjenja</zaj:Ulica>
                    <zaj:Broj>1</zaj:Broj>
                </zaj:Adresa>
                <zaj:Kontakt_podaci>
                	<zaj:Telefon>065/222-3332</zaj:Telefon>
	            	<zaj:Email>jhon.doe@gmail.com</zaj:Email>
	            </zaj:Kontakt_podaci>
                <zaj:Ime>Jhon</zaj:Ime>
                <zaj:Prezime>Doe</zaj:Prezime>
               
                <zaj:Drzavljanstvo>Srpsko</zaj:Drzavljanstvo>
                
                <Pseudonim>Anonimus</Pseudonim>
                <Godina_smrti>2010</Godina_smrti>
            </Autor>
        </Autori>
        
        <Podaci_o_originalu>
            <Identifikator>
                <Naslov>XML-01</Naslov>
            </Identifikator>
        </Podaci_o_originalu>
        
        <!-- <Radni_odnos> Delo stvoreno u radnom odnosu sa FTN-om u Novom Sadu</Radni_odnos> -->
        <Nacin_koriscenja>Delo ce biti korisceno u naucne svrhe</Nacin_koriscenja>
        
    </Autorsko_delo>
    
    
    <Prilozi>
        <Prisutan_opis>true</Prisutan_opis>
        <Prisutan_primer>false</Prisutan_primer>
    </Prilozi>

</Zahtev_za_autorsko_delo>

=== nevenaprokic/XML-project/docs/XMLParsers/data/A1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Zahtev_za_autorsko_delo xmlns="www.ftn.uns.ac.rs/ZahtevZaAutorskoDelo"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="www.ftn.uns.ac.rs/ZahtevZaAutorskoDelo A1.xsd" naslov="ЗАХТЕВ ЗА УНОШЕЊЕ У ЕВИДЕНЦИЈУ И ДЕПОНОВАЊЕ АУТОРСКИХ ДЕЛА">
    <Zavod>
        <Adresa>
            <Mesto>Београд</Mesto>
            <Ulica>Кнегиње Љубице</Ulica>
            <Broj>5</Broj>
        </Adresa>
        <Naziv></Naziv>
    </Zavod>

    <Podnosilac>
        <Pravno_lice>
            <Adresa>
                <Mesto></Mesto>
                <Ulica></Ulica>
                <Broj></Broj>
            </Adresa>
            <Naziv></Naziv>
        </Pravno_lice>
        <Autor>
            <Ime></Ime>
            <Prezime></Prezime>
            <Adresa/>
            <Drzavljanstvo></Drzavljanstvo>
        </Autor>
    </Podnosilac>

    <Autorsko_delo>
        <Identifikator>
            <Naslov></Naslov>
        </Identifikator>
        <Autori>
            <Autor anonimni="true">
                <Ime></Ime>
                <Prezime></Prezime>
                <Adresa>
                    <Mesto></Mesto>
                    <Ulica></Ulica>
                    <Broj></Broj>
                </Adresa>
                <Drzavljanstvo></Drzavljanstvo>
            </Autor>
        </Autori>
    </Autorsko_delo>

</Zahtev_za_autorsko_delo>
